<?php namespace App\Model;

use Framework\Model;
use Framework\Session;

class User extends Model
{
    protected static $table = 'users';
    protected static $fields = [
        // 'id' => 'int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY', // this is automatically created for every model
        'role_id' => 'INT UNSIGNED NOT NULL',
        'email' => 'VARCHAR(255) NOT NULL',
        'username' => 'VARCHAR(255) NOT NULL',
        'credits' => 'INT UNSIGNED NOT NULL',
        'first_name' => 'VARCHAR(255) NOT NULL',
        'last_name' => 'VARCHAR(255) NOT NULL',
        'date_of_birth' => 'VARCHAR(20) NOT NULL',
        'accepts_newsletter' => 'TINYINT UNSIGNED NOT NULL',
        'password' => 'VARCHAR(255) NOT NULL',
        'confirmation' => 'VARCHAR(255) NOT NULL',
        'is_confirmed' => 'TINYINT UNSIGNED NOT NULL',
        'timezone' => 'VARCHAR(50) NOT NULL',
        'language' => 'VARCHAR(10) NOT NULL',
        'country' => 'VARCHAR(2) NOT NULL',
        'is_active' => 'TINYINT UNSIGNED NOT NULL',
    ];

    public static function isLoggedIn()
    {
        return Session::exists('user.id');
        // return ['success' => Session::exists('user.id')];
    }

    public static function isAdmin() {
        $table = self::getTableName();

        $id = is_null(Session::get('user.id')) ? 0 : Session::get('user.id');

        $sql = "
          SELECT id FROM {$table}
          WHERE is_active = :is_active
          AND role_id = :role_id
          AND id = :id AND deleted_at IS NULL
        ";
        $row = self::one($sql, ['is_active' => 1, 'role_id' => 1, 'id' => $id]);
        return isset($row['id']);
    }

    public static function noUsername() {
        $userId = Session::get('user.id');
        $user = User::getById($userId);
        return ($user['username'] == '' ? true : false );
    }

    public static function getSelf()
    {
        $userId = Session::get('user.id');
        $user = User::getById($userId);
        unset($user['password']);
        return $user;
    }

    public static function getActive()
    {
        $table = self::getTableName();

        $sql = "SELECT * FROM {$table} WHERE is_active = :is_active AND deleted_at IS NULL";
        return self::many($sql);
    }

    public static function getIdAndPasswordByEmail($email)
    {
        $binds = ['email' => $email];
        $sql = "SELECT id, password, role_id FROM ". self::getTableName() ." WHERE email = :email AND deleted_at IS NULL";
        return self::one($sql, $binds);
    }

    public static function getByUsername($user)
    {
        $sql = "SELECT id FROM ". self::getTableName() ." WHERE username = :user AND deleted_at IS NULL";
        return self::one($sql, ['user' => $user]);
    }

    public static function getByEmail($email)
    {
        $sql = "SELECT * FROM ". self::getTableName() ." WHERE email = :email AND deleted_at IS NULL";
        $row = self::one($sql, ['email' => $email]);
        unset($row['password']);
        return $row;
    }

    public static function getByConfirmation($code)
    {
        $table = self::getTableName();
        $sql = "SELECT id FROM {$table} WHERE confirmation = :confirmation AND deleted_at IS NULL";
        return self::one($sql, ['confirmation' => $code]);
    }

    public static function getAdmins()
    {
        $table = self::getTableName();

        $sql = "
        SELECT id, username, email, first_name, last_name
        FROM {$table}
        WHERE deleted_at IS NULL
        AND role_id = 1 AND deleted_at IS NULL
        ORDER BY last_name, first_name
        ";
        return self::many($sql);
    }

    public static function getTimeZoneList() {
        return [
            "America/Adak",
            "America/Argentina/Buenos_Aires",
            "America/Argentina/La_Rioja",
            "America/Argentina/San_Luis",
            "America/Atikokan",
            "America/Belem",
            "America/Boise",
            "America/Caracas",
            "America/Chihuahua",
            "America/Cuiaba",
            "America/Denver",
            "America/El_Salvador",
            "America/Godthab",
            "America/Guatemala",
            "America/Hermosillo",
            "America/Indiana/Tell_City",
            "America/Inuvik",
            "America/Kentucky/Louisville",
            "America/Lima",
            "America/Managua",
            "America/Mazatlan",
            "America/Mexico_City",
            "America/Montreal",
            "America/Nome",
            "America/Ojinaga",
            "America/Port-au-Prince",
            "America/Rainy_River",
            "America/Rio_Branco",
            "America/Santo_Domingo",
            "America/St_Barthelemy",
            "America/St_Vincent",
            "America/Tijuana",
            "America/Whitehorse",
            "America/Anchorage",
            "America/Argentina/Catamarca",
            "America/Argentina/Mendoza",
            "America/Argentina/Tucuman",
            "America/Atka",
            "America/Belize",
            "America/Buenos_Aires",
            "America/Catamarca",
            "America/Coral_Harbour",
            "America/Curacao",
            "America/Detroit",
            "America/Ensenada",
            "America/Goose_Bay",
            "America/Guayaquil",
            "America/Indiana/Indianapolis",
            "America/Indiana/Vevay",
            "America/Iqaluit",
            "America/Kentucky/Monticello",
            "America/Los_Angeles",
            "America/Manaus",
            "America/Mendoza",
            "America/Miquelon",
            "America/Montserrat",
            "America/Noronha",
            "America/Panama",
            "America/Port_of_Spain",
            "America/Rankin_Inlet",
            "America/Rosario",
            "America/Sao_Paulo",
            "America/St_Johns",
            "America/Swift_Current",
            "America/Toronto",
            "America/Winnipeg",
            "America/Anguilla",
            "America/Argentina/ComodRivadavia",
            "America/Argentina/Rio_Gallegos",
            "America/Argentina/Ushuaia",
            "America/Bahia",
            "America/Blanc-Sablon",
            "America/Cambridge_Bay",
            "America/Cayenne",
            "America/Cordoba",
            "America/Danmarkshavn",
            "America/Dominica",
            "America/Fort_Wayne",
            "America/Grand_Turk",
            "America/Guyana",
            "America/Indiana/Knox",
            "America/Indiana/Vincennes",
            "America/Jamaica",
            "America/Knox_IN",
            "America/Louisville",
            "America/Marigot",
            "America/Menominee",
            "America/Moncton",
            "America/Nassau",
            "America/North_Dakota/Beulah",
            "America/Pangnirtung",
            "America/Porto_Acre",
            "America/Recife",
            "America/Santa_Isabel",
            "America/Scoresbysund",
            "America/St_Kitts",
            "America/Tegucigalpa",
            "America/Tortola",
            "America/Yakutat",
            "America/Antigua",
            "America/Argentina/Cordoba",
            "America/Argentina/Salta",
            "America/Aruba",
            "America/Bahia_Banderas",
            "America/Boa_Vista",
            "America/Campo_Grande",
            "America/Cayman",
            "America/Costa_Rica",
            "America/Dawson",
            "America/Edmonton",
            "America/Fortaleza",
            "America/Grenada",
            "America/Halifax",
            "America/Indiana/Marengo",
            "America/Indiana/Winamac",
            "America/Jujuy",
            "America/Kralendijk",
            "America/Lower_Princes",
            "America/Martinique",
            "America/Merida",
            "America/Monterrey",
            "America/New_York",
            "America/North_Dakota/Center",
            "America/Paramaribo",
            "America/Porto_Velho",
            "America/Regina",
            "America/Santarem",
            "America/Shiprock",
            "America/St_Lucia",
            "America/Thule",
            "America/Vancouver",
            "America/Yellowknife",
            "America/Araguaina",
            "America/Argentina/Jujuy",
            "America/Argentina/San_Juan",
            "America/Asuncion",
            "America/Barbados",
            "America/Bogota",
            "America/Cancun",
            "America/Chicago",
            "America/Creston",
            "America/Dawson_Creek",
            "America/Eirunepe",
            "America/Glace_Bay",
            "America/Guadeloupe",
            "America/Havana",
            "America/Indiana/Petersburg",
            "America/Indianapolis",
            "America/Juneau",
            "America/La_Paz",
            "America/Maceio",
            "America/Matamoros",
            "America/Metlakatla",
            "America/Montevideo",
            "America/Nipigon",
            "America/North_Dakota/New_Salem",
            "America/Phoenix",
            "America/Puerto_Rico",
            "America/Resolute",
            "America/Santiago",
            "America/Sitka",
            "America/St_Thomas",
            "America/Thunder_Bay",
            "America/Virgin",
            "Indian/Antananarivo",
            "Indian/Kerguelen",
            "Indian/Reunion",
            "Australia/ACT",
            "Australia/Currie",
            "Australia/Lindeman",
            "Australia/Perth",
            "Australia/Victoria",
            "Europe/Amsterdam",
            "Europe/Berlin",
            "Europe/Chisinau",
            "Europe/Helsinki",
            "Europe/Kiev",
            "Europe/Madrid",
            "Europe/Moscow",
            "Europe/Prague",
            "Europe/Sarajevo",
            "Europe/Tallinn",
            "Europe/Vatican",
            "Europe/Zagreb",
            "Pacific/Apia",
            "Pacific/Efate",
            "Pacific/Galapagos",
            "Pacific/Johnston",
            "Pacific/Marquesas",
            "Pacific/Noumea",
            "Pacific/Ponape",
            "Pacific/Tahiti",
            "Pacific/Wallis",
            "Indian/Chagos",
            "Indian/Mahe",
            "Australia/Adelaide",
            "Australia/Darwin",
            "Australia/Lord_Howe",
            "Australia/Queensland",
            "Australia/West",
            "Europe/Andorra",
            "Europe/Bratislava",
            "Europe/Copenhagen",
            "Europe/Isle_of_Man",
            "Europe/Lisbon",
            "Europe/Malta",
            "Europe/Nicosia",
            "Europe/Riga",
            "Europe/Simferopol",
            "Europe/Tirane",
            "Europe/Vienna",
            "Europe/Zaporozhye",
            "Pacific/Auckland",
            "Pacific/Enderbury",
            "Pacific/Gambier",
            "Pacific/Kiritimati",
            "Pacific/Midway",
            "Pacific/Pago_Pago",
            "Pacific/Port_Moresby",
            "Pacific/Tarawa",
            "Pacific/Yap",
            "Africa/Abidjan",
            "Africa/Asmera",
            "Africa/Blantyre",
            "Africa/Ceuta",
            "Africa/Douala",
            "Africa/Johannesburg",
            "Africa/Kinshasa",
            "Africa/Lubumbashi",
            "Africa/Mbabane",
            "Africa/Niamey",
            "Africa/Timbuktu",
            "Africa/Accra",
            "Africa/Bamako",
            "Africa/Brazzaville",
            "Africa/Conakry",
            "Africa/El_Aaiun",
            "Africa/Juba",
            "Africa/Lagos",
            "Africa/Lusaka",
            "Africa/Mogadishu",
            "Africa/Nouakchott",
            "Africa/Tripoli",
            "Africa/Addis_Ababa",
            "Africa/Bangui",
            "Africa/Bujumbura",
            "Africa/Dakar",
            "Africa/Freetown",
            "Africa/Kampala",
            "Africa/Libreville",
            "Africa/Malabo",
            "Africa/Monrovia",
            "Africa/Ouagadougou",
            "Africa/Tunis",
            "Africa/Algiers",
            "Africa/Banjul",
            "Africa/Cairo",
            "Africa/Dar_es_Salaam",
            "Africa/Gaborone",
            "Africa/Khartoum",
            "Africa/Lome",
            "Africa/Maputo",
            "Africa/Nairobi",
            "Africa/Porto-Novo",
            "Africa/Windhoek",
            "Africa/Asmara",
            "Africa/Bissau",
            "Africa/Casablanca",
            "Africa/Djibouti",
            "Africa/Harare",
            "Africa/Kigali",
            "Africa/Luanda",
            "Africa/Maseru",
            "Africa/Ndjamena",
            "Africa/Sao_Tome",
            "Atlantic/Azores",
            "Atlantic/Faroe",
            "Atlantic/St_Helena",
            "Atlantic/Bermuda",
            "Atlantic/Jan_Mayen",
            "Atlantic/Stanley",
            "Atlantic/Canary",
            "Atlantic/Madeira",
            "Atlantic/Cape_Verde",
            "Atlantic/Reykjavik",
            "Atlantic/Faeroe",
            "Atlantic/South_Georgia",
            "Asia/Aden",
            "Asia/Aqtobe",
            "Asia/Baku",
            "Asia/Calcutta",
            "Asia/Dacca",
            "Asia/Dushanbe",
            "Asia/Hong_Kong",
            "Asia/Jayapura",
            "Asia/Kashgar",
            "Asia/Kuala_Lumpur",
            "Asia/Magadan",
            "Asia/Novokuznetsk",
            "Asia/Pontianak",
            "Asia/Riyadh",
            "Asia/Shanghai",
            "Asia/Tehran",
            "Asia/Ujung_Pandang",
            "Asia/Vladivostok",
            "Asia/Almaty",
            "Asia/Ashgabat",
            "Asia/Bangkok",
            "Asia/Choibalsan",
            "Asia/Damascus",
            "Asia/Gaza",
            "Asia/Hovd",
            "Asia/Jerusalem",
            "Asia/Kathmandu",
            "Asia/Kuching",
            "Asia/Makassar",
            "Asia/Novosibirsk",
            "Asia/Pyongyang",
            "Asia/Saigon",
            "Asia/Singapore",
            "Asia/Tel_Aviv",
            "Asia/Ulaanbaatar",
            "Asia/Yakutsk",
            "Asia/Amman",
            "Asia/Ashkhabad",
            "Asia/Beirut",
            "Asia/Chongqing",
            "Asia/Dhaka",
            "Asia/Harbin",
            "Asia/Irkutsk",
            "Asia/Kabul",
            "Asia/Katmandu",
            "Asia/Kuwait",
            "Asia/Manila",
            "Asia/Omsk",
            "Asia/Qatar",
            "Asia/Sakhalin",
            "Asia/Taipei",
            "Asia/Thimbu",
            "Asia/Ulan_Bator",
            "Asia/Yekaterinburg",
            "Asia/Anadyr",
            "Asia/Baghdad",
            "Asia/Bishkek",
            "Asia/Chungking",
            "Asia/Dili",
            "Asia/Hebron",
            "Asia/Istanbul",
            "Asia/Kamchatka",
            "Asia/Kolkata",
            "Asia/Macao",
            "Asia/Muscat",
            "Asia/Oral",
            "Asia/Qyzylorda",
            "Asia/Samarkand",
            "Asia/Tashkent",
            "Asia/Thimphu",
            "Asia/Urumqi",
            "Asia/Yerevan",
            "Asia/Aqtau",
            "Asia/Bahrain",
            "Asia/Brunei",
            "Asia/Colombo",
            "Asia/Dubai",
            "Asia/Ho_Chi_Minh",
            "Asia/Jakarta",
            "Asia/Karachi",
            "Asia/Krasnoyarsk",
            "Asia/Macau",
            "Asia/Nicosia",
            "Asia/Phnom_Penh",
            "Asia/Rangoon",
            "Asia/Seoul",
            "Asia/Tbilisi",
            "Asia/Tokyo",
            "Asia/Vientiane",
            "Australia/Canberra",
            "Australia/LHI",
            "Australia/NSW",
            "Australia/Tasmania",
            "Australia/Broken_Hill",
            "Australia/Hobart",
            "Australia/North",
            "Australia/Sydney",
            "Pacific/Chuuk",
            "Pacific/Fiji",
            "Pacific/Guam",
            "Pacific/Kwajalein",
            "Pacific/Niue",
            "Pacific/Pitcairn",
            "Pacific/Saipan",
            "Pacific/Truk",
            "Pacific/Chatham",
            "Pacific/Fakaofo",
            "Pacific/Guadalcanal",
            "Pacific/Kosrae",
            "Pacific/Nauru",
            "Pacific/Palau",
            "Pacific/Rarotonga",
            "Pacific/Tongatapu",
            "Pacific/Easter",
            "Pacific/Funafuti",
            "Pacific/Honolulu",
            "Pacific/Majuro",
            "Pacific/Norfolk",
            "Pacific/Pohnpei",
            "Pacific/Samoa",
            "Pacific/Wake",
            "Antarctica/Casey",
            "Antarctica/McMurdo",
            "Antarctica/Vostok",
            "Antarctica/Davis",
            "Antarctica/Palmer",
            "Antarctica/DumontDUrville",
            "Antarctica/Rothera",
            "Antarctica/Macquarie",
            "Antarctica/South_Pole",
            "Antarctica/Mawson",
            "Antarctica/Syowa",
            "Arctic/Longyearbyen",
            "Europe/Athens",
            "Europe/Brussels",
            "Europe/Dublin",
            "Europe/Istanbul",
            "Europe/Ljubljana",
            "Europe/Mariehamn",
            "Europe/Oslo",
            "Europe/Rome",
            "Europe/Skopje",
            "Europe/Tiraspol",
            "Europe/Vilnius",
            "Europe/Zurich",
            "Europe/Belfast",
            "Europe/Bucharest",
            "Europe/Gibraltar",
            "Europe/Jersey",
            "Europe/London",
            "Europe/Minsk",
            "Europe/Paris",
            "Europe/Samara",
            "Europe/Sofia",
            "Europe/Uzhgorod",
            "Europe/Volgograd",
            "Europe/Belgrade",
            "Europe/Budapest",
            "Europe/Guernsey",
            "Europe/Kaliningrad",
            "Europe/Luxembourg",
            "Europe/Monaco",
            "Europe/Podgorica",
            "Europe/San_Marino",
            "Europe/Stockholm",
            "Europe/Vaduz",
            "Europe/Warsaw",
            "Indian/Cocos",
            "Indian/Mauritius",
            "Indian/Christmas",
            "Indian/Maldives",
            "Indian/Comoro",
            "Indian/Mayotte",
            "Australia/Brisbane",
            "Australia/Eucla",
            "Australia/Melbourne",
            "Australia/South",
            "Australia/Yancowinna",
        ];
    }

    public static function getCountries() {
        return [
            "US" => "United States",
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "DZ" => "Algeria",
            "AS" => "American Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarctica",
            "AG" => "Antigua and Barbuda",
            "AR" => "Argentina",
            "AM" => "Armenia",
            "AW" => "Aruba",
            "AU" => "Australia",
            "AT" => "Austria",
            "AZ" => "Azerbaijan",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesh",
            "BB" => "Barbados",
            "BY" => "Belarus",
            "BE" => "Belgium",
            "BZ" => "Belize",
            "BJ" => "Benin",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivia",
            "BA" => "Bosnia and Herzegovina",
            "BW" => "Botswana",
            "BV" => "Bouvet Island",
            "BR" => "Brazil",
            "BQ" => "British Antarctic Territory",
            "IO" => "British Indian Ocean Territory",
            "VG" => "British Virgin Islands",
            "BN" => "Brunei",
            "BG" => "Bulgaria",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Cambodia",
            "CM" => "Cameroon",
            "CA" => "Canada",
            "CT" => "Canton and Enderbury Islands",
            "CV" => "Cape Verde",
            "KY" => "Cayman Islands",
            "CF" => "Central African Republic",
            "TD" => "Chad",
            "CL" => "Chile",
            "CN" => "China",
            "CX" => "Christmas Island",
            "CC" => "Cocos [Keeling] Islands",
            "CO" => "Colombia",
            "KM" => "Comoros",
            "CG" => "Congo - Brazzaville",
            "CD" => "Congo - Kinshasa",
            "CK" => "Cook Islands",
            "CR" => "Costa Rica",
            "HR" => "Croatia",
            "CU" => "Cuba",
            "CY" => "Cyprus",
            "CZ" => "Czech Republic",
            "CI" => "Côte d’Ivoire",
            "DK" => "Denmark",
            "DJ" => "Djibouti",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "NQ" => "Dronning Maud Land",
            "DD" => "East Germany",
            "EC" => "Ecuador",
            "EG" => "Egypt",
            "SV" => "El Salvador",
            "GQ" => "Equatorial Guinea",
            "ER" => "Eritrea",
            "EE" => "Estonia",
            "ET" => "Ethiopia",
            "FK" => "Falkland Islands",
            "FO" => "Faroe Islands",
            "FJ" => "Fiji",
            "FI" => "Finland",
            "FR" => "France",
            "GF" => "French Guiana",
            "PF" => "French Polynesia",
            "TF" => "French Southern Territories",
            "FQ" => "French Southern and Antarctic Territories",
            "GA" => "Gabon",
            "GM" => "Gambia",
            "GE" => "Georgia",
            "DE" => "Germany",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Greece",
            "GL" => "Greenland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GG" => "Guernsey",
            "GN" => "Guinea",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard Island and McDonald Islands",
            "HN" => "Honduras",
            "HK" => "Hong Kong SAR China",
            "HU" => "Hungary",
            "IS" => "Iceland",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IM" => "Isle of Man",
            "IL" => "Israel",
            "IT" => "Italy",
            "JM" => "Jamaica",
            "JP" => "Japan",
            "JE" => "Jersey",
            "JT" => "Johnston Island",
            "JO" => "Jordan",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KI" => "Kiribati",
            "KW" => "Kuwait",
            "KG" => "Kyrgyzstan",
            "LA" => "Laos",
            "LV" => "Latvia",
            "LB" => "Lebanon",
            "LS" => "Lesotho",
            "LR" => "Liberia",
            "LY" => "Libya",
            "LI" => "Liechtenstein",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "MO" => "Macau SAR China",
            "MK" => "Macedonia",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malta",
            "MH" => "Marshall Islands",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MU" => "Mauritius",
            "YT" => "Mayotte",
            "FX" => "Metropolitan France",
            "MX" => "Mexico",
            "FM" => "Micronesia",
            "MI" => "Midway Islands",
            "MD" => "Moldova",
            "MC" => "Monaco",
            "MN" => "Mongolia",
            "ME" => "Montenegro",
            "MS" => "Montserrat",
            "MA" => "Morocco",
            "MZ" => "Mozambique",
            "MM" => "Myanmar [Burma]",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "AN" => "Netherlands Antilles",
            "NT" => "Neutral Zone",
            "NC" => "New Caledonia",
            "NZ" => "New Zealand",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolk Island",
            "KP" => "North Korea",
            "VD" => "North Vietnam",
            "MP" => "Northern Mariana Islands",
            "NO" => "Norway",
            "OM" => "Oman",
            "PC" => "Pacific Islands Trust Territory",
            "PK" => "Pakistan",
            "PW" => "Palau",
            "PS" => "Palestinian Territories",
            "PA" => "Panama",
            "PZ" => "Panama Canal Zone",
            "PG" => "Papua New Guinea",
            "PY" => "Paraguay",
            "YD" => "People's Democratic Republic of Yemen",
            "PE" => "Peru",
            "PH" => "Philippines",
            "PN" => "Pitcairn Islands",
            "PL" => "Poland",
            "PT" => "Portugal",
            "PR" => "Puerto Rico",
            "QA" => "Qatar",
            "RO" => "Romania",
            "RU" => "Russia",
            "RW" => "Rwanda",
            "RE" => "Réunion",
            "BL" => "Saint Barthélemy",
            "SH" => "Saint Helena",
            "KN" => "Saint Kitts and Nevis",
            "LC" => "Saint Lucia",
            "MF" => "Saint Martin",
            "PM" => "Saint Pierre and Miquelon",
            "VC" => "Saint Vincent and the Grenadines",
            "WS" => "Samoa",
            "SM" => "San Marino",
            "SA" => "Saudi Arabia",
            "SN" => "Senegal",
            "RS" => "Serbia",
            "CS" => "Serbia and Montenegro",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapore",
            "SK" => "Slovakia",
            "SI" => "Slovenia",
            "SB" => "Solomon Islands",
            "SO" => "Somalia",
            "ZA" => "South Africa",
            "GS" => "South Georgia and the South Sandwich Islands",
            "KR" => "South Korea",
            "ES" => "Spain",
            "LK" => "Sri Lanka",
            "SD" => "Sudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard and Jan Mayen",
            "SZ" => "Swaziland",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syria",
            "ST" => "São Tomé and Príncipe",
            "TW" => "Taiwan",
            "TJ" => "Tajikistan",
            "TZ" => "Tanzania",
            "TH" => "Thailand",
            "TL" => "Timor-Leste",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad and Tobago",
            "TN" => "Tunisia",
            "TR" => "Turkey",
            "TM" => "Turkmenistan",
            "TC" => "Turks and Caicos Islands",
            "TV" => "Tuvalu",
            "UM" => "U.S. Minor Outlying Islands",
            "PU" => "U.S. Miscellaneous Pacific Islands",
            "VI" => "U.S. Virgin Islands",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "SU" => "Union of Soviet Socialist Republics",
            "AE" => "United Arab Emirates",
            "GB" => "United Kingdom",
            "ZZ" => "Unknown or Invalid Region",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VU" => "Vanuatu",
            "VA" => "Vatican City",
            "VE" => "Venezuela",
            "VN" => "Vietnam",
            "WK" => "Wake Island",
            "WF" => "Wallis and Futuna",
            "EH" => "Western Sahara",
            "YE" => "Yemen",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe",
            "AX" => "Åland Islands",
        ];
    }
}
