#!/usr/bin/env php
<?php namespace Ascend\Core;

class CommandLineArguments {
	
	private static $cmdArguments;
	
	public static function setArgv($a) {
		self::$cmdArguments = $a;
	}
	
	public static function getArgv() {
		return self::$cmdArguments;
	}
}
CommandLineArguments::setArgv($argv);

require_once 'bootstrap.php';
exit;